apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: wnsvy607/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              valueFrom: 
                configMapKeyRef:
                  name: data-store-env
                  key: folder
              # value: 'story'
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim: 
            claimName: host-pvc

          # emptyDir 타입의 드라이버
          # emptyDir: {}

          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate