apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      # 외부로 노출할 Port
      port: 80
      # 컨테이너가 EXPOSE 하는 Port
      targetPort: 3000